# Makefile for hello pass

# Indicate where we are relative to the top of the source tree.
LEVEL = ../..

# Name of the library to build
LIBRARYNAME = patternsExtractor

# Make the shared library become a loadable module so the tools can 
# dlopen/dlsym on the resulting library.
LOADABLE_MODULE = 1

# Include the makefile implementation stuff
include $(LEVEL)/Makefile.common
